# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160531_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='nit_cliente',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Cliente'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TipoEquipo'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Equipo'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='fecha_fin',
            field=models.DateField(blank=True, default=datetime.date(2016, 11, 30), null=True),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='garantia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Garantia'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Tecnico'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='tipo_incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.TipoIncidencia'),
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
